#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
  echo 'Usage: ./dev

Runs the development server

'
  exit
fi

cd "$(dirname "$0")"

main() {
  cd ../
  bun install
  bun run dev
}

main "$@"