version: '3.6'

services:
  nginx:
    image: boilerplate-svelte/nginx:$VERSION
    build:
      context: .
      dockerfile: ./ci/nginx/Dockerfile
      args:
        - VERSION=${VERSION:-latest}
    env_file: ./.env.${BUILD_ENV}
    healthcheck:
      test: curl --fail http://localhost:8081/status || exit 1
      timeout: 2s
      interval: 10s
      retries: 12
      start_period: 10s
    restart: unless-stopped
